# Created from scripts/singleuse/Dockerfile :
image: tristpinsm/ch_util_unittest:latest
pipelines:
  default:
    - step:
        # Run unit tests
        script:
            - pip3 install --upgrade pip
            - pip2 install --upgrade pip

            # Work around bad Debian/pip interaction
            # See https://github.com/pypa/pip/issues/5221
            - hash -r pip2
            - hash -r pip3

            - pip2 install future
            - pip3 install future

            # Forcibly install numpy first in python2, to avoid the h5py
            # setup.py from pulling in a numpy 0.17 release candidate.
            - pip2 install numpy==1.16

            - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial pip2 install -r requirements.txt
            - python2 -m unittest discover ch_util/tests/
            - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial pip3 install -r requirements.txt
            - python3 -m unittest discover ch_util/tests/
    - step:
        # Parsed by bitbucket-pipelines to mirror repository to github on push.
        script:
          - git config --global push.default simple
          - git push -f git@github.com:CHIMEFRB/ch_util.git
